services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy  
    ports:
      - "8080:8080"
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    depends_on:
      db:
        condition: service_healthy  
      mq:
        condition: service_healthy  

  db:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      TARGET_DB: app_db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        - CMD-SHELL
        - |
          mariadb -e 'SHOW DATABASES' | grep $${TARGET_DB} | [ $$(wc -l) -eq 1 ]
      interval: 10s
      timeout: 5s
      retries: 3

  mq:
    image: rabbitmq:3-management
    volumes:
      - ./initmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./initmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test:
        - CMD-SHELL
        - |
          rabbitmq-diagnostics list_queues -q | [ $$(wc -l) -eq 2 ]
      interval: 10s
      timeout: 5s
      retries: 5